import Head from "next/head";
import Appbar from "@/components/Appbar";
import styles from "@/styles/Home.module.css";
// import Hero from "";
import StarsCanvas from "@/components/canvas/Stars";
import About from "@/components/About";
import WorkExperience from "@/components/WorkExperience";
import Hero from "@/components/Hero";
import Tech from "@/components/Tech";
import Projects from "@/components/Projects";
import EarthCanvas from "@/components/canvas/Earth";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Appbar />
        <div style={{ position: "relative", zIndex: "-99" }}>
          <StarsCanvas />
        </div>
        <Hero />

        <About />
        <WorkExperience />
        <Tech />
        <div style={{ position: "relative", zIndex: "-99" }}>
          <StarsCanvas />
        </div>
        <Projects />
        <Contact />
        {/* <EarthCanvas /> */}
      </main>
    </>
  );
}

